[target.arm-unknown-linux-gnueabi]
# https://github.com/wpilibsuite/opensdk
# TODO: set this to the default location based on host OS?
# or require users to add it to PATH
linker = "tools/roborio-academic/bin/arm-frc2023-linux-gnueabi-gcc"
rustflags = [
  "-C", "target-cpu=cortex-a9",
]

[build]
target = "arm-unknown-linux-gnueabi"
